engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
  config:
    languages:
      - ruby
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
- bin/**/*
exclude_paths:
- doc/**/*
- images/**/*
