##
# UA-Tester
# BSecTeam (C) 2015 - 2015
##
---
firefox:
 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,
 Accept-Language: pt-BR,pt;q=0.8,en-US;q=0.5,en;q=0.3,
 Accept-Encoding: gzip, deflate,
 Connection: keep-alive
safari:
 Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8,
 Accept-Language: pt-br,
 Accept-Encoding: gzip, deflate,
 Connection: keep-alive
chrome:
 Accept: text/css,*/*;q=0.1,
 Accept-Language: en-US,en;q=0.8,
 Accept-Encoding: gzip, deflate,sdch,
 Connection: keep-alive
